version: '3.8'

services:
  express-server:
    container_name: express-{{project_name}}
    restart: always
    build:
      context: .
    environment:
      - DOCKER_ENV=true
      - BASE_URL
      - SUPABASE_URL
      - SUPABASE_KEY
      - SUPABASE_JWT_SECRET
    stdin_open: true
    tty: true
    ports:
      - '{{be_port}}8:{{be_port}}8'
    networks:
      - supabase_network_express-{{project_name}}

networks:
  supabase_network_express-{{project_name}}:
    external: true
